apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::243981255342:role/eksctl-eksctl-demo-nodegroup-ng-2-NodeInstanceRole-V0UY13RKARUM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::243981255342:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-05T00:14:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1720"
  uid: 04e4aafe-7bfe-42e4-b56c-c85c29dca257
